#!/bin/sh
#
# Copyright (c) 2016 Daniel P. Smith, Apertus Solutions, LLC
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. /usr/lib/openxt/key-functions
[ $? -eq 0 ] || {
    echo "failed to load key-functions"
    exit 1
}

. /usr/lib/tpm-scripts/tpm-functions
[ $? -eq 0 ] || {
    echo "failed to load tpm-functions"
    exit 1
}

get_preferred_alg () {
    pcr_bank_exists "sha256" && echo "sha256" && return 0
    pcr_bank_exists "sha1" && echo "sha1" && return 0
    return 1
}

hex2bin() {
    read hex
    echo -n $hex | sed 's/\([0-9A-F]\{2\}\)/\\\\\\x\1/gI' | xargs printf
}

# Function to parse grub.cfg and return all multiboot modules and their
#   full command line
# parameter 0: path to grub.conf
parse_grub() {
    local grub_conf=$1
    exec 6< $grub_conf

    # Find any environment variables and bring them into current environment
    local IFS=$'\n'
    local lines=$(egrep -e "^[A-Z_]*=.*" $grub_conf)
    env_list=""
    for line in $lines; do
        local key=$(echo $line|cut -f 1 -d'=')
        local value=$(echo $line|cut -f 2- -d'='|cut -f 1 -d';'|tr -d \")

        env_list="${env_list} ${key}"
        declare "env_${key}=${value}"
    done

    # Find the default boot entry
    local entry=$( grep "set default=" $grub_conf | cut -f2 -d= | tr -d \" )
    [[ -z $entry ]] && entry=0

    # Seek to default boot entry
    local count=0
    while read -u 6 line; do
        echo $line | grep -q menuentry || continue

        if [[ $count -lt $entry ]]; then
            count=$(( $count + 1 ))
            continue
        elif [[ $count -eq $entry ]]; then
            break
        elif [[ $count -gt $entry ]]; then
            exec 6<&-
            return 1;
        fi
    done

    # Parse through entry lines, expanding variables, and printing any multiboot modules
    local IFS=' '
    while read -u 6 line; do
        echo $line | grep -q -e "^#" && continue
        echo $line | grep -q -e "^}" && break

        line=$(echo $line | sed -e 's/(/\\(/' -e 's/)/\\)/')
        line=$(echo $line | awk '$1 ~ /multiboot|module/ { print substr($0, index($0,$2)) }')
        for e in $(echo "$env_list"); do
            if echo $line|grep -q $e; then
                local var=$(eval "echo env_${e}")
                local sub=$(eval echo \$${var})
                local match="s|\$${e}|${sub}|"
                line=$(echo $line|sed -e "${match}")
            fi
        done
        echo $line
    done

    exec 6<&-
}

# Function to parse openxt.cfg and return all modules and their filename
# parameter 0: path to openxt.conf
parse_eficfg() {
    local efi_conf=$1
    local default=0
    local xen=""
    local linux=""
    local initrd=""
    local xsm=""
    local ucode=""

    exec 6< $efi_conf
    while read -u 6 line; do
        [ "$line" == "[openxt-normal]" ] && default=1
        [ $default -eq 1 -a "$line" == "" ] && break

        [ -z "$xen" ] && xen=$(echo -n $line | grep "options" | sed 's/options=/\/boot\/xen.efi /g')
        [ -z "$linux" ] && linux=$(echo -n $line | grep "kernel" | sed 's/kernel=/\/boot\/bzImage /g')
        [ -z "$initrd" ] && initrd=$(echo -n $line | grep "ramdisk" | sed 's/ramdisk=/\/boot\/initrd /g')
        [ -z "$xsm" ] && xsm=$(echo -n $line | grep "xsm" | sed 's/xsm=/\/etc\/xen\/xenrefpolicy\/policy\/policy.24 /g')
        [ -z "$ucode" ] && ucode=$(echo -n $line | grep "ucode" | sed 's/ucode=/\/boot\/microcode_intel.bin /g')
    done

    printf "\n$xen\n$linux\n$initrd\n$xsm\n$ucode"

    exec 6<&-
}

# Function to perform a TPM hash extended
# parameter 0: hash to extend
# parameter 1: extending hash
# return 0 on success
# return 1 if passed invalid hashes
hash_extend() {
    local first=$1
    local second=$2
    local hashalg=${3:-"sha1"}
    local buffer="/tmp/.buffer"

    case $hashalg in
        "sha1")
            [[ $first == 0 ]] && first="0000000000000000000000000000000000000000"
            [[ $(echo -n $first|wc -c) -ne 40 ]] && return 1
            [[ $(echo -n $second|wc -c) -ne 40 ]] && return 1
        ;;
        "sha256")
            [[ $first == 0 ]] && \
                first="0000000000000000000000000000000000000000000000000000000000000000"
            [[ $(echo -n $first|wc -c) -ne 64 ]] && return 1
            [[ $(echo -n $second|wc -c) -ne 64 ]] && return 1
        ;;
    esac

    echo -n $first | hex2bin >$buffer
    echo -n $second | hex2bin >>$buffer

    echo $(${hashalg}sum $buffer | awk '{ print $1 }')

    rm $buffer
}

# Mount debugfs on /sys/kernel/debug when not already mounted, needed for DRTM event log
ensure_debugfs() {
    if [ -r /proc/mounts ] && \
        awk '$2 == "/sys/kernel/debug" && $3 == "debugfs" { exit 0 } END { exit 1 }' /proc/mounts
    then
        return 0
    fi
    mkdir -p /sys/kernel/debug 2>/dev/null
    mount -t debugfs none /sys/kernel/debug 2>/dev/null
}

# Function to obtain a local copy of the slaunch DRTM event log
get_slaunch_eventlog() {
    local out_file
    local log_src="/sys/kernel/debug/slaunch_eventlog/raw.bin"

    out_file="$(mktemp /tmp/slaunch-eventlog.bin)" || return 1

    ensure_debugfs

    if [ -r "${log_src}" ]; then
        cp "${log_src}" "${out_file}" || {
            rm -f "${out_file}"
            return 1
        }
        echo "${out_file}"
        return 0
    fi

    echo "get_slaunch_eventlog: failed to read log" >&2
    rm -f "${out_file}"
    return 1
}

# Parse TCG event log and print: pcr|event_type|digest|event_data
parse_slaunch_evtlog() {
    local evtlog="${1}"
    local hashalg="${2:-sha256}"
    local parser_out=""
    local alg_label

    [ -r "${evtlog}" ] || return 1

    case "${hashalg}" in
        sha256) alg_label="SHA256" ;;
        sha1)   alg_label="SHA1" ;;
        *) return 1 ;;
    esac

    if command -v openxt-tpm2-evt-log-parser >/dev/null 2>&1; then
        parser_out="$(openxt-tpm2-evt-log-parser "${evtlog}" 2>/dev/null)" || return 1
    elif command -v tpm2_eventlog >/dev/null 2>&1; then
        parser_out="$(tpm2_eventlog "${evtlog}" 2>/dev/null)" || return 1
    else
        return 1
    fi

    echo "${parser_out}" | awk -v alg="${alg_label}" '
        BEGIN { inentry=0; pcr=""; etype=""; digest=""; event="" }
        /^Entry [0-9]+:/ {
            inentry=1;
            pcr=""; etype=""; digest=""; event="";
            next;
        }
        inentry && /^[[:space:]]+PCR:[[:space:]]+/ {
            pcr=$2;
            next;
        }
        inentry && /^[[:space:]]+Event Type:[[:space:]]+/ {
            etype=$3;
            next;
        }
        inentry && $0 ~ ("^[[:space:]]+" alg ":[[:space:]]+") {
            line=$0;
            sub("^[[:space:]]+" alg ":[[:space:]]+", "", line);
            digest=tolower(line);
            next;
        }
        inentry && /^[[:space:]]+Event:[[:space:]]*/ {
            line=$0;
            sub(/^[[:space:]]+Event:[[:space:]]*/, "", line);
            event=line;
            if (pcr != "" && etype != "" && digest != "")
                printf "%s|%s|%s|%s\n", pcr, etype, digest, event;
            inentry=0;
            next;
        }
    '
}

# Build a simple module map for event-data based substitution:
#   keyword|path
build_module_map() {
    local root="${1:-/}"
    local conf="${2}"
    local srtm="${3:-1}"
    local modules=""
    local module
    local full
    local base

    if [ "${srtm}" -eq 1 ]; then
        modules="$(parse_eficfg "${conf}")" || return 1
    else
        modules="$(parse_grub "${root}/${conf}")" || return 1
    fi

    local IFS=$'\n'
    for modline in ${modules}; do
        module="$(echo "${modline}" | awk '{ print $1 }')"
        [ -n "${module}" ] || continue

        case "${module}" in
            /*) full="${module}" ;;
            *) full="${root}/${module}" ;;
        esac
        base="$(basename "${module}")"
        printf "%s|%s\n" "${base}" "${full}"
    done

    # Print common aliases present
    printf "xen|/boot/xen.efi\n"
    printf "hypervisor|/boot/xen.efi\n"
    printf "bzimage|/boot/bzImage\n"
    printf "kernel|/boot/bzImage\n"
    printf "initrd|/boot/initrd\n"
    printf "policy|/etc/xen/xenrefpolicy/policy/policy.24\n"
    printf "xsm|/etc/xen/xenrefpolicy/policy/policy.24\n"
    printf "microcode|/boot/microcode_intel.bin\n"
}

resolve_slaunch_event_file() {
    local event_desc="$(echo "${1}" | tr 'A-Z' 'a-z')"
    local map_file="${2}"

    [ -r "${map_file}" ] || return 1

    while IFS='|' read -r key file_path; do
        [ -n "${key}" ] || continue
        echo "${event_desc}" | grep -Fq "${key}" || continue

        if [ -r "${file_path}" ]; then
            echo "${file_path}"
            return 0
        fi
    done < "${map_file}"

    return 1
}

match_acm() {
    local root="${1}"
    local acm=""

    for f in ${root}/boot/*.{bin,BIN}; do
        if acmmatch "${f}" >/dev/null; then
            acm="${f}"
            break;
        fi
    done

    echo "${acm}"
}

# Function to generate the TrenchBoot verified launch policy
# parameter 0: TPM owner password
# return 0 on success
# return 1 on failure to create policy
# return 2 on failure to write the policy to the TPM
generate_policy() {
    local password=$(cat $1)
    local policy=/tmp/trenchboot.vl
    local hash_alg="sha1" #default to sha1 for legacy support

    is_tpm_2_0
    local tpm2=$?

    if [[ "${tpm2}" -eq 0 ]]; then
        hash_alg=$(get_preferred_alg)
        [[ $? -ne 0 ]] && echo "No valid algs available" && return 1
        #Two possible nv index locations on tpm2.0 that TrenchBoot checks
        local trenchboot_idx='0x01200001'
        local trenchboot_idx2='0x01c10131'
    else
        local trenchboot_idx='0x20000001'
    fi

    create_policy $policy $hash_alg
    [[ $? -ne 0 ]] && echo "failed to create Verified Launch policy" && return 1

    local polsize=$(cat $policy | wc -c)
    if [ "${tpm2}" -eq 0 ]; then
        tpm2_write_trenchboot_policy "${policy}" "${trenchboot_idx}" "${password}"
        if [ $? -ne 0 ]; then
            echo "failed to write TrenchBoot Verified Launch policy to TPM" >&2
            return 2
        fi
        tpm2_write_trenchboot_policy "${policy}" "${trenchboot_idx2}" "${password}"
    else
        local old_policy=/tmp/old-trenchboot.vl
        local old_polsize

        lcp_readpol -i $trenchboot_idx -f "$old_policy" >/dev/null 2>&1

        # old_policy might not have been created.
        touch "$old_policy"

        # If the current policy matches, we are done
        diff -q "$old_policy" "$policy" >/dev/null 2>&1 && {
            rm -f "$old_policy"
            rm -f "$policy"
            return 0
        }

        old_polsize=$( cat "$old_policy" 2>/dev/null | wc -c )
        rm -f "$old_policy"

        if [ $old_polsize -ne $polsize ]; then
            # Delete even if it doesn't exist, but don't error out
            tpmnv_relindex -i $trenchboot_idx -p "$password" 1>/dev/null 2>&1
            tpmnv_defindex -i $trenchboot_idx -s $polsize -pv 0x02 \
                           -p "$password" 1>/dev/null 2>&1 || {
                echo "Failed to create TrenchBoot TPM NVRAM index $trenchboot_idx" >&2
                return 2
            }
        fi

        lcp_writepol -i $trenchboot_idx -f $policy -p "$password" 1>/dev/null 2>&1
    fi

    if [[ $? -ne 0 ]]; then
        echo "failed to write TrenchBoot Verified Launch policy to TPM" >&2
        return 2
    fi

    [[ -f $policy ]] && rm -f $policy
}

# Function to create policy and store into a file
# parameter 0: path where policy file should be written
# parameter 1: hash algorithm to use, either sha1 or sha256
# return 0 on success
# return 1 if fails to read
create_policy() {
    local policy=$1
    local hash_alg=${2:-"sha256"}

    case "$hash_alg" in
        sha1|sha256) ;;
        *) echo "invalid algorithm" >&2; return 1 ;;
    esac

    : > "$policy" || {
        echo "failed to create placeholder TrenchBoot policy file" >&2
        return 1
    }

    return 0
}

# TrenchBoot PCR pre-calculator for forward sealing.
# output: "<pcr17> <pcr18> <pcr19>"
calculate_slaunch_pcrs() {
    local root="${1:-/}"
    local conf="${2}"
    local hashalg="${3:-sha256}"
    local srtm="${4:-1}"
    local evtlog=""
    local events=""
    local events_file=""
    local map_file=""
    local p17="0"
    local p18="0"
    local p19=""

    case "${hashalg}" in
        sha1|sha256) ;;
        *) return 1 ;;
    esac

    evtlog="$(get_slaunch_eventlog)" || return 1
    map_file="$(mktemp /tmp/slaunch-modmap)" || {
        rm -f "${evtlog}"
        return 1
    }

    build_module_map "${root}" "${conf}" "${srtm}" > "${map_file}" || {
        rm -f "${evtlog}" "${map_file}"
        return 1
    }

    events="$(parse_slaunch_evtlog "${evtlog}" "${hashalg}")" || {
        rm -f "${evtlog}" "${map_file}"
        return 1
    }

    events_file="$(mktemp /tmp/slaunch-events)" || {
        rm -f "${evtlog}" "${map_file}"
        return 1
    }
    printf '%s\n' "${events}" > "${events_file}"

    while IFS='|' read -r pcr etype digest event_desc; do
        local event_digest="${digest}"
        local file_path=""

        [ -n "${pcr}" ] || continue
        [ -n "${event_digest}" ] || continue

        # TrenchBoot launch measurements are carried in 0x502 events.
        if [ "${etype}" = "0x502" ]; then
            file_path="$(resolve_slaunch_event_file "${event_desc}" "${map_file}")" || true
            if [ -n "${file_path}" ]; then
                event_digest="$(${hashalg}sum "${file_path}" | awk '{ print $1 }')"
            fi
        fi

        case "${pcr}" in
            17)
                p17="$(hash_extend "${p17}" "${event_digest}" "${hashalg}")" || {
                    rm -f "${evtlog}" "${map_file}" "${events_file}"
                    return 1
                }
                ;;
            18)
                p18="$(hash_extend "${p18}" "${event_digest}" "${hashalg}")" || {
                    rm -f "${evtlog}" "${map_file}" "${events_file}"
                    return 1
                }
                ;;
        esac
    done < "${events_file}"

    p19="$(tpm_get_pcr 19 2>/dev/null || true)"
    [ -n "${p19}" ] || p19="0"

    rm -f "${evtlog}" "${map_file}" "${events_file}"
    echo "${p17} ${p18} ${p19}"
    return 0
}

write_config_pcrs() {
    local root="${1:-/}"
    local pcrs="0 1 2 3 4 5 7 8 15 17 18 19"

    echo "$pcrs" > ${root}/config/config.pcrs
}

# Function to configure measured launch on platform.  The next boot will cause
#   init-root.ro to perform first sealing operation.
# parameter 0: mount point for rootfs
# parameter 1: key to unlock partition
# parameter 2: device path for partition
# return 0 on success
#        1 on error
configure_measured_launch()
{
    local root="${1:-/}"
    local unlock_key="${2}"
    local config_dev="${3}"
    local tpm_dir="${root}/boot/system/tpm"

    # this will block until there is sufficient entropy
    local key_file=$(gen_config_key $root) || return 1
    set_encrypted_key $unlock_key $key_file $config_dev || return 1

    write_config_pcrs "${root}"

    mkdir -p ${tpm_dir}
    touch ${tpm_dir}/setup
    touch ${tpm_dir}/enabled

    echo "${key_file}"
    return 0
}
